volumes:
  caddy_data:

services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
